# One status per entry
activities = [
    "Bracing for the next dad joke...",
    "Counting sheep to fall asleep... but they keep turning into Python",
    "Counting up to infinity in binary",
    "Crafting the next 'bonk' in advance",
    "Ctrl+C, Ctrl+V",
    "Error 404 - Status not found",
    "Hiding from the Windows updates process 😨",
    "I like my cookies byte-sized",
    "Learning how to speak French",
    "Listening to Snap's microphone",
    "Listening to Snaptraks practicing guitar (save me)",
    "Listening to some electronic music",
    "Listening to you ramble",
    "Lurking in the Hatventures Community's Teamspeak server",
    "Playing Minecraft",
    "Sarcasm.exe has stopped working",
    "Scrolling Reddit for cat videos",
    "Searching for hidden easter eggs",
    "Sending virtual hugs to whoever wants one",
    "Shopping for a new hat",
    "Sudo make me a sandwich 🥪",
    "Watching Short Circuit",
    "Watching Snap in the shower",
    "Watching The Terminator",
    "Watching my code being written",
    "Watching the Matrix being edited",
    "Watching you cuties",
    "Witty comebacks exhausted, please check in a few",
    "World Domination Progess: 1E-40 %",
]
