[rarity]
    common   = 75
    rare     = 5
    uncommon = 20

[blessed_rarity]
    common   = 0
    rare     = 20
    uncommon = 80

[[trick_or_treaters]]
    common   = "Space Trash"
    image    = "https://archives.snaptraks.phd/Halloween/Alien.png"
    name     = "Alien"
    rare     = "Levitation Belt"
    uncommon = "Silver Pants"

[[trick_or_treaters]]
    common   = "Assorted Bugs"
    image    = "https://archives.snaptraks.phd/Halloween/Bat.png"
    name     = "Bat"
    rare     = "Tropical Flower"
    uncommon = "Cool Geode"

[[trick_or_treaters]]
    common   = "Hairball"
    image    = "https://archives.snaptraks.phd/Halloween/Cat.png"
    name     = "Cat"
    rare     = "Can Of Tuna"
    uncommon = "Toy Mouse"

[[trick_or_treaters]]
    common   = "Smushed Pumpkin"
    image    = "https://archives.snaptraks.phd/Halloween/Centaur.png"
    name     = "Centaur"
    rare     = "Huge Hoof"
    uncommon = "Spooky Lantern"

[[trick_or_treaters]]
    common   = "Goat Horns"
    image    = "https://archives.snaptraks.phd/Halloween/Chupacabra.png"
    name     = "Chupacabra"
    rare     = "Wool Sweater"
    uncommon = "Cherry Slushie"

[[trick_or_treaters]]
    common   = "Balloon Animal"
    image    = "https://archives.snaptraks.phd/Halloween/Clown.png"
    name     = "Clown"
    rare     = "Clown Egg"
    uncommon = "Prank Flower"

[[trick_or_treaters]]
    common   = "Broken Twigs"
    image    = "https://archives.snaptraks.phd/Halloween/Crow.png"
    name     = "Crow"
    rare     = "Shiny Bauble"
    uncommon = "Cold Fries"

[[trick_or_treaters]]
    common   = "Brimstone"
    image    = "https://archives.snaptraks.phd/Halloween/Demon.png"
    name     = "Demon"
    rare     = "Inferno Hot Sauce"
    uncommon = "Pitchfork"

[[trick_or_treaters]]
    common   = "Pixie Dust"
    image    = "https://archives.snaptraks.phd/Halloween/Fairy.png"
    name     = "Fairy"
    rare     = "Teeny Wand"
    uncommon = "Tiny Boots"

[[trick_or_treaters]]
    common   = "Swamp Gas"
    image    = "https://archives.snaptraks.phd/Halloween/Frog.png"
    name     = "Frog"
    rare     = "Miniature Crown"
    uncommon = "Lily Pad"

[[trick_or_treaters]]
    common   = "Drop Of Ectoplasm"
    image    = "https://archives.snaptraks.phd/Halloween/Ghost.png"
    name     = "Ghost"
    rare     = "Mostly Unfinished Business"
    uncommon = "Rattlin' Chains"

[[trick_or_treaters]]
    common   = "Lucky Rock"
    image    = "https://archives.snaptraks.phd/Halloween/Goblin.png"
    name     = "Goblin"
    rare     = "Half-Eaten Chocolate Bar"
    uncommon = "Chewed Shoe"

[[trick_or_treaters]]
    common   = "Glitching Gizmo"
    image    = "https://archives.snaptraks.phd/Halloween/Gremlin.png"
    name     = "Gremlin"
    rare     = "Twitchy Tablet"
    uncommon = "Sparking Smartphone"

[[trick_or_treaters]]
    common   = "Eerie Acorn"
    image    = "https://archives.snaptraks.phd/Halloween/Haunted-Tree.png"
    name     = "Haunted Tree"
    rare     = "Evil Syrup"
    uncommon = "Poison Apple"

[[trick_or_treaters]]
    common   = "Creepy Candle"
    image    = "https://archives.snaptraks.phd/Halloween/Jackolantern.png"
    name     = "Jack O' Lantern"
    rare     = "Pumpkin's Ghost"
    uncommon = "Sinister Vine"

[[trick_or_treaters]]
    common   = "Bent Feather"
    image    = "https://archives.snaptraks.phd/Halloween/Knight.png"
    name     = "Knight"
    rare     = "Enchanted Blade"
    uncommon = "Shiny Helmet"

[[trick_or_treaters]]
    common   = "Wet Kelp"
    image    = "https://archives.snaptraks.phd/Halloween/Man-shark.png"
    name     = "Manshark"
    rare     = "Postcard From Atlantis"
    uncommon = "Snorkel And Fins"

[[trick_or_treaters]]
    common   = "Broken Lightbulb"
    image    = "https://archives.snaptraks.phd/Halloween/Mothman.png"
    name     = "Mothman"
    rare     = "Blurry Photo"
    uncommon = "Owl Feathers"

[[trick_or_treaters]]
    common   = "Box Of Bandages"
    image    = "https://archives.snaptraks.phd/Halloween/Mummy.png"
    name     = "Mummy"
    rare     = "Book Of The Dead"
    uncommon = "Papyrus Scroll"

[[trick_or_treaters]]
    common   = "Roasted Seeds"
    image    = "https://archives.snaptraks.phd/Halloween/Nice-Pumpkins.png"
    name     = "Nice Pumpkins"
    rare     = "Perfect Pie"
    uncommon = "Hearty Soup"

[[trick_or_treaters]]
    common   = "Bowl Of Orcslop"
    image    = "https://archives.snaptraks.phd/Halloween/Orc.png"
    name     = "Orc"
    rare     = "Sweet Battleaxe"
    uncommon = "Wicked Dagger"

[[trick_or_treaters]]
    common   = "Crusty Barnacle"
    image    = "https://archives.snaptraks.phd/Halloween/Pirate.png"
    name     = "Pirate"
    rare     = "Gold'n Doubloon"
    uncommon = "Fearsome Eyepatch"

[[trick_or_treaters]]
    common   = "Cough Drop"
    image    = "https://archives.snaptraks.phd/Halloween/Plague-Doctor.png"
    name     = "Plague Doctor"
    rare     = "Gloomy Mask"
    uncommon = "Fragrant Herbs"

[[trick_or_treaters]]
    common   = "Tiny Crumbs"
    image    = "https://archives.snaptraks.phd/Halloween/Rat.png"
    name     = "Rat"
    rare     = "Magic Flute"
    uncommon = "Fine Cheeseboard"

[[trick_or_treaters]]
    common   = "Chilly Chess Piece"
    image    = "https://archives.snaptraks.phd/Halloween/Reaper.png"
    name     = "Reaper"
    rare     = "Shivering Scythe"
    uncommon = "Souvenir Hourglass"

[[trick_or_treaters]]
    common   = "Confusing Captchas"
    image    = "https://archives.snaptraks.phd/Halloween/Robot.png"
    name     = "Robot"
    rare     = "Techno Mixtape"
    uncommon = "Positron Relay"

[[trick_or_treaters]]
    common   = "Short Straw"
    image    = "https://archives.snaptraks.phd/Halloween/Scarecrow.png"
    name     = "Scarecrow"
    rare     = "Golden Corn"
    uncommon = "Ragged Hat"

[[trick_or_treaters]]
    common   = "Empty Test Tube"
    image    = "https://archives.snaptraks.phd/Halloween/Scientist.png"
    name     = "Scientist"
    rare     = "Shrink Ray"
    uncommon = "Tesla Coil"

[[trick_or_treaters]]
    common   = "Glass Of Milk"
    image    = "https://archives.snaptraks.phd/Halloween/Skeleton.png"
    name     = "Skeleton"
    rare     = "Grinning Skull"
    uncommon = "Funny Bone"

[[trick_or_treaters]]
    common   = "Sour Jelly"
    image    = "https://archives.snaptraks.phd/Halloween/Slime.png"
    name     = "Slime"
    rare     = "Prizewinning Preserves"
    uncommon = "Gourmet Jam"

[[trick_or_treaters]]
    common   = "Baby Rattle"
    image    = "https://archives.snaptraks.phd/Halloween/Snake.png"
    name     = "Snake"
    rare     = "Cool Eyepatch"
    uncommon = "Feather Boa"

[[trick_or_treaters]]
    common   = "Cobwebs"
    image    = "https://archives.snaptraks.phd/Halloween/Spider.png"
    name     = "Spider"
    rare     = "Spidersilk Robe"
    uncommon = "Eight Tiny Shoes"

[[trick_or_treaters]]
    common   = "Chewed Up Tennis Ball"
    image    = "https://archives.snaptraks.phd/Halloween/Stabby-Corgi.png"
    name     = "Stabby Corgi"
    rare     = "Slobber Covered Knife"
    uncommon = "Half Eaten Block of Cheese"

[[trick_or_treaters]]
    common   = "Spare Button"
    image    = "https://archives.snaptraks.phd/Halloween/Teddy-Bear.png"
    name     = "Teddy Bear"
    rare     = "Picnic Basket"
    uncommon = "Bag Of Rags"

[[trick_or_treaters]]
    common   = "Used Toothpick"
    image    = "https://archives.snaptraks.phd/Halloween/Vampire.png"
    name     = "Vampire"
    rare     = "Blood-Red Brooch"
    uncommon = "Cape Coupon"

[[trick_or_treaters]]
    common   = "Shedded Fur"
    image    = "https://archives.snaptraks.phd/Halloween/Werewolf.png"
    name     = "Werewolf"
    rare     = "Moonstone"
    uncommon = "Wolf Claw"

[[trick_or_treaters]]
    common   = "Eye Of Newt"
    image    = "https://archives.snaptraks.phd/Halloween/Witch.png"
    name     = "Witch"
    rare     = "Witches' Brew"
    uncommon = "Toe Of Frog"

[[trick_or_treaters]]
    common   = "Wumpling Soup"
    image    = "https://archives.snaptraks.phd/Halloween/Wumpus-Wumpus.png"
    name     = "Wumpus Wumpus"
    rare     = "Wumpkin Spice Latte"
    uncommon = "Wumpernickel Bread"

[[trick_or_treaters]]
    common   = "Fossil Footprint"
    image    = "https://archives.snaptraks.phd/Halloween/Wumpus-Dino.png"
    name     = "Wumpus Dino"
    rare     = "Meteorite Chunk"
    uncommon = "Corprolite"

[[trick_or_treaters]]
    common   = "Gnawed Bones"
    image    = "https://archives.snaptraks.phd/Halloween/Wumpus-Yeti.png"
    name     = "Yeti"
    rare     = "Mountaineer's Hat"
    uncommon = "Snowball"

[[trick_or_treaters]]
    common   = "Peabrain"
    image    = "https://archives.snaptraks.phd/Halloween/Zombie.png"
    name     = "Zombie"
    rare     = "Galaxy Brain"
    uncommon = "Basic Brain"

[[treats]]
    emoji = "🍫"
    name  = "Chocolate"

[[treats]]
    emoji = "🍪"
    name  = "Cookie"

[[treats]]
    emoji = "🧁"
    name  = "Cupcake"

[[treats]]
    emoji = "🍩"
    name  = "Doughnut"

[[treats]]
    emoji = "🍦"
    name  = "Ice Cream"

[[treats]]
    emoji = "🍭"
    name  = "Lollipop"

[[treats]]
    emoji = "🍿"
    name  = "Popcorn"

[[treats]]
    emoji = "🥨"
    name  = "Pretzel"

[[treats]]
    emoji = "🍬"
    name  = "Sweet"

[cursed_names]
    emojis = [
        "🌕",
        "🎃",
        "🐸",
        "👻",
        "👽",
        "💀",
        "🕷️",
        "🕸️",
        "😈",
        "👹",
        "😨",
        "🤡",
        "🦇",
        "🧛",
        "🦄",
        "🧟",
        "🧜",
        "⚰️",
        "🪦",
        "🧙",
        "🔮",
        "🩸",
        "🧠",
    ]
    first_names = [
        "Abraham",
        "Adrian",
        "Alaric",
        "Anastasia",
        "Anton",
        "Astrid",
        "Baron",
        "Bellatrix",
        "Bert",
        "Blair",
        "Bram",
        "Carmilla",
        "Carrie",
        "Casanova",
        "Casper",
        "Claudia",
        "Damien",
        "Dolores",
        "Drac",
        "Drusilla",
        "Edgar",
        "Elena",
        "Elspeth",
        "Elvira",
        "Endora",
        "Ezekiel",
        "Fester",
        "Grendel",
        "Hannibal",
        "Hans",
        "Hecate",
        "Hector",
        "Ichabod",
        "Igor",
        "Jezebel",
        "Lady",
        "Lilith",
        "Lord",
        "Ludmilla",
        "Lugosi",
        "Luna",
        "Madame",
        "Mara",
        "Misty",
        "Morticia",
        "Nyx",
        "Obediah",
        "Otto",
        "Pandora",
        "Raven",
        "Ricardo",
        "Sabrina",
        "Scarlett",
        "Selene",
        "Señor",
        "Sibyl",
        "Solomon",
        "Stanley",
        "Tabitha",
        "Vasily",
        "Viktor",
        "Vlad",
    ]
    last_names = [
        "Bloodstone",
        "Cobweb",
        "Crimson",
        "Darkspell",
        "Demonbreath",
        "Devilstein",
        "Diablo",
        "Doom",
        "Fang",
        "Fleshington",
        "Frankenranken",
        "Fungus",
        "Ghostbreath",
        "Ghostface",
        "Gravestone",
        "Hellblade",
        "McBiteyface",
        "McGhoul",
        "McPutrid",
        "McSlaughter",
        "Moonshadow",
        "Necrofunk",
        "Nightfall",
        "Nightshade",
        "Nocturne",
        "O'Banshee",
        "O'Goblin",
        "O'Skeleton",
        "O'Warlock",
        "Poisonflower",
        "Revenant",
        "Rott",
        "Styx",
        "Velvet",
        "Witchbriar",
    ]
